<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NombreSocioNegocio</name>
   <tag></tag>
   <elementGuidId>be6b8c8e-74ef-4054-9349-9718929f35d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-tabpanel-0&quot;]/div/div[1]/p-dropdown/div/div[3]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
